# Example usage:
#     docker build -t pdnscontrol-proxy . && docker run -p 80:80 --link pdnscontrol --name pdnscontrol-proxy pdnscontrol-proxy
#
# Then point your browser to http://dockerhost:80/

FROM debian:testing

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install nginx-full && \
    rm -rf /var/lib/apt/lists/*

RUN echo "daemon off;" >> /etc/nginx/nginx.conf
WORKDIR /etc/nginx/sites-enabled

RUN rm default
RUN set -x && \
    echo "# generated by dockerfile" > site.conf && \
    echo "server {" >> site.conf && \
    echo "  listen 80 default_server;" >> site.conf && \
    echo "  location / {" >> site.conf && \
    echo "    proxy_pass http://pdnscontrol:5000;" >> site.conf && \
    echo "    proxy_redirect    http://pdnscontrol:5000/ /;" >> site.conf && \
    echo "    proxy_set_header Host \$http_host;" >> site.conf && \
    echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;" >> site.conf && \
    echo "  }" >> site.conf && \
    echo "}" >> site.conf && \
    true && cat site.conf

EXPOSE 80
CMD ["nginx"]

